import { expect } from '@playwright/test';
import { test, tvHost } from '../support/tv-fixture.js';
import { openTvWorkspace } from '../support/dashboard.js';

test('dashboard adds the first TV, opens remote and returns without another pairing or TV mutation', async ({ page, tv }) => {
  await tv.setupAndLogin(page);
  await expect(page.getByRole('heading', { name: 'Пока нет телевизоров' })).toBeVisible();
  await expect(page.getByLabel('IP-адрес телевизора')).toHaveCount(0);
  await openTvWorkspace(page);
  await page.getByLabel('IP-адрес телевизора').fill(tvHost);
  await page.getByRole('button', { name: 'Подключить', exact: true }).click();
  await tv.tv.waitForRequestCount(1);
  tv.promptGate.release();
  await expect(page.getByRole('button', { name: /^Открыть телевизор / })).toBeVisible();
  const card = page.getByRole('button', { name: /^Открыть телевизор / });
  await expect(page.getByRole('button', { name: 'Открыть пульт', exact: true })).toHaveCount(0);
  await expect(page.locator('.device-card button')).toHaveCount(1);
  await card.hover();
  await expect(card).toHaveCSS('border-color', 'rgb(131, 189, 206)');
  await expect(page.getByRole('heading', { name: 'Телевизоры', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Добавить ТВ' })).toBeVisible();
  await page.setViewportSize({ width: 795, height: 1248 });
  const add = page.getByRole('button', { name: 'Добавить ТВ' });
  const alignment = await add.evaluate((button) => {
    const text = [...button.childNodes].find((node) => node.nodeType === Node.TEXT_NODE && node.textContent?.includes('Добавить ТВ'))!;
    const range = document.createRange(); range.selectNodeContents(text);
    const label = range.getBoundingClientRect();
    const icon = button.querySelector('svg')!.getBoundingClientRect();
    return { centerDifference: Math.abs(icon.y + icon.height / 2 - label.y - label.height / 2), gap: label.x - icon.right };
  });
  expect(alignment.centerDifference).toBeLessThan(2);
  expect(alignment.gap).toBeGreaterThanOrEqual(8);
  const mutations: string[] = [];
  page.on('request', (request) => { if (request.method() !== 'GET') mutations.push(request.url()); });
  await openTvWorkspace(page);
  await expect(page.getByRole('button', { name: 'Вверх', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Телевизоры', exact: true }).click();
  await expect(page.getByRole('group', { name: 'Пульт', exact: true })).toHaveCount(0);
  await page.keyboard.press('ArrowUp');
  await page.getByRole('button', { name: 'Настройки', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Настройки аккаунта' })).toBeVisible();
  await expect(page.getByLabel('MAC-адрес телевизора')).toHaveCount(0);
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(page.getByRole('button', { name: /^Открыть телевизор / })).toBeVisible();
  await expect(page.locator('body')).not.toContainText(tvHost);
  await page.setViewportSize({ width: 320, height: 800 });
  const bounds = (await card.boundingBox())!;
  expect(bounds.x).toBeGreaterThanOrEqual(0);
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(320);
  await card.focus();
  await card.press('Enter');
  await expect(page.getByRole('group', { name: 'Пульт', exact: true })).toBeVisible();
  expect(mutations).toEqual([]);
  expect(tv.promptCount).toBe(1);
});
