import { expect } from '@playwright/test';
import { test, tvHost } from '../support/tv-fixture.js';
import { openTvWorkspace } from '../support/dashboard.js';

test('Add TV keeps the platform arrow inset and opens shared account settings', async ({ page, tv }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1100 });
  await tv.setupAndLogin(page);
  await page.getByRole('button', { name: 'Добавить ТВ' }).click();
  const select = page.getByRole('combobox', { name: 'Платформа телевизора' });
  await expect(select).toHaveCSS('appearance', 'none');
  const bounds = (await select.boundingBox())!;
  const arrow = (await select.locator('..').locator('svg').boundingBox())!;
  expect(bounds.x + bounds.width - arrow.x - arrow.width).toBe(12);
  expect(Math.abs(bounds.y + bounds.height / 2 - arrow.y - arrow.height / 2)).toBeLessThan(1);
  await select.selectOption('tizen');
  await expect(select).toHaveValue('tizen');
  await page.screenshot({ path: testInfo.outputPath('add-tv-platform.png'), fullPage: true });
  await page.getByRole('button', { name: 'Настройки', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Настройки аккаунта' })).toBeVisible();
  await expect(page.getByLabel('MAC-адрес телевизора')).toHaveCount(0);
  await page.getByRole('button', { name: 'Закрыть настройки' }).click();
  await expect(page.getByRole('button', { name: 'Настройки', exact: true })).toBeFocused();
});

test('dashboard adds the first TV, opens remote and returns without another pairing or TV mutation', async ({ page, tv }) => {
  await tv.setupAndLogin(page);
  await expect(page.getByRole('heading', { name: 'Пока нет телевизоров' })).toBeVisible();
  await expect(page.getByLabel('IP-адрес телевизора')).toHaveCount(0);
  await openTvWorkspace(page);
  await page.getByLabel('IP-адрес телевизора').fill(tvHost);
  await page.getByRole('button', { name: 'Подключить', exact: true }).click();
  await tv.tv.waitForRequestCount(1);
  tv.promptGate.release();
  await expect(page.getByRole('button', { name: /^Открыть телевизор / })).toBeVisible();
  const card = page.getByRole('button', { name: /^Открыть телевизор / });
  await expect(page.getByRole('button', { name: 'Открыть пульт', exact: true })).toHaveCount(0);
  await expect(page.locator('.device-card button')).toHaveCount(2);
  await expect(page.locator('.device-card').getByRole('button', { name: /^Открыть телевизор / })).toHaveCount(1);
  await expect(page.locator('.device-card').getByRole('button', { name: /^Удалить телевизор / })).toHaveCount(1);
  await card.hover();
  await expect(card).toHaveCSS('border-color', 'rgb(131, 189, 206)');
  await expect(page.getByRole('heading', { name: 'Телевизоры', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Добавить ТВ' })).toBeVisible();
  const badge = page.locator('.platform-badge');
  const logo = badge.getByRole('img', { name: 'LG', exact: true });
  const badgeBounds = (await badge.boundingBox())!;
  const logoBounds = (await logo.boundingBox())!;
  expect(logoBounds.width).toBeGreaterThan(34);
  expect(logoBounds.x).toBeGreaterThan(badgeBounds.x);
  expect(logoBounds.y).toBeGreaterThan(badgeBounds.y);
  expect(logoBounds.y + logoBounds.height).toBeLessThan(badgeBounds.y + badgeBounds.height);
  await logo.evaluate((image) => { (image as HTMLElement).style.transform = 'none'; });
  expect(await badge.boundingBox()).toEqual(badgeBounds);
  await logo.evaluate((image) => { (image as HTMLElement).style.removeProperty('transform'); });
  await page.setViewportSize({ width: 795, height: 1248 });
  const add = page.getByRole('button', { name: 'Добавить ТВ' });
  const alignment = await add.evaluate((button) => {
    const text = [...button.childNodes].find((node) => node.nodeType === Node.TEXT_NODE && node.textContent?.includes('Добавить ТВ'))!;
    const range = document.createRange(); range.selectNodeContents(text);
    const label = range.getBoundingClientRect();
    const icon = button.querySelector('svg')!.getBoundingClientRect();
    return { centerDifference: Math.abs(icon.y + icon.height / 2 - label.y - label.height / 2), gap: label.x - icon.right };
  });
  expect(alignment.centerDifference).toBeLessThan(2);
  expect(alignment.gap).toBeGreaterThanOrEqual(8);
  const mutations: string[] = [];
  page.on('request', (request) => { if (request.method() !== 'GET') mutations.push(request.url()); });
  await openTvWorkspace(page);
  await expect(page.getByRole('button', { name: 'Вверх', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Телевизоры', exact: true }).click();
  await expect(page.getByRole('group', { name: 'Пульт', exact: true })).toHaveCount(0);
  await page.keyboard.press('ArrowUp');
  await page.getByRole('button', { name: 'Настройки', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Настройки аккаунта' })).toBeVisible();
  await expect(page.getByLabel('MAC-адрес телевизора')).toHaveCount(0);
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(page.getByRole('button', { name: /^Открыть телевизор / })).toBeVisible();
  await expect(page.locator('body')).not.toContainText(tvHost);
  await page.setViewportSize({ width: 320, height: 800 });
  const bounds = (await card.boundingBox())!;
  expect(bounds.x).toBeGreaterThanOrEqual(0);
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(320);
  await card.focus();
  await card.press('Enter');
  await expect(page.getByRole('group', { name: 'Пульт', exact: true })).toBeVisible();
  expect(mutations).toEqual([]);
  expect(tv.promptCount).toBe(1);
});
